### ISSUE TITLE
Dedicated container or machine as alternative to lambdas

### ISSUE THREAD

**Issue by akutruff** [sst/open-next#111]
For many reasons, it can be advantageous to simply run the webserver in a Fargate container to avoid cold start problems as well as mitigate DB connection limit issues.  At the same time, it is desirable to have ISR and static content served from S3.  Any chance there could be support for this?

**Comment by jayair** [comment]
Yeah we are thinking about it, can you drop this in #research-fargate on Discord?

**Comment by khuezy** [comment]
I haven't done it myself, but look at: https://docs.sst.dev/constructs/Service
I plan on using this in the future, will update when I do.

**Comment by akutruff** [comment]
@khuezy Just to verify since this is closed - I can setup a next.js site with all the bells and whistles of ISR with S3 that I mentioned with Fargate rather than lambdas?

**Comment by conico974** [comment]
@akutruff You can, but you'll have to do it by yourself. 
You'll have to use the [incremental cache](https://nextjs.org/docs/app/api-reference/next-config-js/incrementalCacheHandlerPath) and copy parts of the code from open-next and sst.
Just to give you some direction:
- https://github.com/sst/open-next/blob/main/packages/open-next/src/adapters/cache.ts
- https://github.com/sst/open-next/blob/24c5166377346bed1a029fb2223cf7f3b52a10d3/packages/open-next/src/build.ts#L394C4-L509

**Comment by conico974** [comment]
Just a little warning though regarding the default filesystem incremental cache.
If you plan to have a lot of traffic and you're using app dir, i strongly advise you to not use the default filesystem approach with EFS.

**Comment by akutruff** [comment]
@conico974 Thanks for the reply!

> You can, but you'll have to do it by yourself. You'll have to use the [incremental cache](https://nextjs.org/docs/app/api-reference/next-config-js/incrementalCacheHandlerPath) and copy parts of the code from open-next and sst. Just to give you some direction:

That's cool and it sounds like it is possible.  I was wondering if this is something that could be more officially supported in the project.  I'm always reluctant to snap parts of OSS projects as things change and keeping up with bug fixes etc. is non-obvious.  Serverless vs. Fargate  is now becoming a more common discussion as far as I've seen, and this is the one big piece of Next.js that's missing.

**Comment by conico974** [comment]
That's something on my mind, but it will need some significant work to make it work.
We talked about a rewrite of the server that could allow this. But it will not be before v3.

**Comment by akutruff** [comment]
Cool thanks for letting me know.  Glad to hear it's potentially on the roadmap.

**Comment by khuezy** [comment]
You can follow the discussion here: https://discord.com/channels/983865673656705025/1164872233223729152
I recently experimented w/ fly.io deployment and I don't think I can recommend Lambdas now... fly.io lets you scale your containers down to 0 or have it scale to as large as you need (within their capacity).

When a Fly container shuts down, it takes <1s to boot up again vs 3s cold start on lambdas...
Logs are tail-able in real time and you can ship it to Loki or Datadog compared to 5 minute delay + CW fees...
You can run the latest Node version to get all its benefits vs waiting years for AWS to support the runtime...

There's a lot more benefits too... but we still need to figure a way to handle ISR/CDN.

**Comment by conico974** [comment]
It's ready to test if you want https://open-next.js.org/v3

**Comment by ludalex** [comment]
> It's ready to test if you want https://open-next.js.org/v3

The link is not working. Have there been development on this? 

Would be super interesting for our project and to adopt ion/open-next.

**Comment by conico974** [comment]
@ludalex All the docs have migrated to V3 actually, we just forgot to add a redirection.

From the OpenNext perspective, everything should be ready for Container or even dedicated machines, you just need a [custom config file](https://open-next.js.org/config) and set the override wrapper and converter to node, for everything that you'd want deployed on node. See the pageSsr in the config for an example.

As for the IAC part, nothing is done yet in Ion or SST V2, you could take a look at the [reference implementation](https://open-next.js.org/reference-implementation) which includes the possibility to deploy some part on AWS App Runner. It should be possible to replicate this reference implementation in Ion using the AWS provider in pulumi.

I know that there is a few bugs in this reference implementation, you can look at the ones used in the e2e tests https://github.com/sst/open-next/blob/v3-rc/examples/sst/stacks/OpenNextReferenceImplementation.ts , it doesn't have AppRunner support, but you can just use the `createAppRunnerOrigin` function from the docs

**Comment by conico974** [comment]
Fixed in [V3](https://github.com/sst/open-next/releases/tag/v3.0.0)
No IAC tools implements it yet, but it's there
