### ISSUE TITLE
CloudFront Functions - Middlewares

### ISSUE THREAD

**Issue by dhruvdutt** [sst/open-next#112]
## 💡 Idea 

Add support for middleware build output to deploy on [CF Functions](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions.html).

## Use-case It Solves

The current build output for middleware is only compatible with Lambda@Edge which have cold start issues and restrictions around geolocation headers for viewer request event and is only present in 13 regional caches worldwide.

Based on the [deployment documentation](https://nextjs.org/docs/app/building-your-application/deploying) in Next.js
> [Middleware](https://nextjs.org/docs/pages/building-your-application/routing/middleware) is automatically optimized as [Edge Functions](https://vercel.com/features/edge-functions?utm_source=next-site&utm_medium=docs&utm_campaign=next-website) that have zero cold starts and boot instantly

Next.js + Vercel deploy middlewares on their [Edge Functions](https://vercel.com/docs/concepts/limits/overview#functions-comparison) which are built on top of CF Functions.

Making the open-next build output for middlewares compatible with CF Functions would help improve the performance and current challenges with Lambda@Edge.

CF Functions Viewer Request has access to geolocation and CF headers that are needed to solving most common use-cases for using middlewares.

## Additional Information

- [AWS - Lambda@Edge vs CF Functions](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions.html)
- [AWS - Restrictions on Lambda@Edge & CF Functions](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions-restrictions.html)

**Comment by fwang** [comment]
Hey @dhruvdutt, CloudFront functions support a very minimal set of node API and do not support async calls, which are often used in middleware.

Vercel uses CloudFlare functions which support a wider set of node APIs and are more powerful.

Let me know if that makes sense.

**Comment by dhruvdutt** [comment]
@fwang The current approach with Lambda@Edge has been limiting things for use cases which don't require any fetch async calls. The cold start issues with Lambda@Edge don't make it an ideal platform.

Does it make sense to provide a build output option for both platforms Lambda@Edge & CloudFront Functions?

**Comment by iagomelanias** [comment]
That would be great. For [SaaS platforms](https://github.com/vercel/platforms), it would increase performance significantly since middlewares are used for rewriting the response only. No async calls are made.

**Comment by conico974** [comment]
I'll close this one as it is not possible to implement in cloudfront functions
@iDVB The rc is available if you want to try https://open-next.js.org/v3

**Comment by med8bra** [comment]
Hello @conico974, I'm using correctly Cloudfront functions alongside opennext and I believe it's maybe now easier to bundle next middleware for the new [CF js v2.0 runtime ](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/functions-javascript-runtime-20.html) which supports a wider APIs/syntax including (async/await).

Do you think there will still be challenges with the new runtime? Maybe it can be an opt-in as it introduces limitations to the middleware in terms of code size and available APIs

**Comment by conico974** [comment]
@med8bra Nope still impossible, an empty middleware alone is probably already way bigger than what's possible to deploy on cloudfront functions. And I'm not even talking about all the missing api that are not available in CF functions (like fetch).
But with OpenNext you can use your own cloudfront functions in front of Next if you want to.
