### ISSUE TITLE
RFC: Add unit testing

### ISSUE THREAD

**Issue by khuezy** [sst/open-next#118]
At a minimum, we should have some unit testing of some utils function to ensure robustness of open-next.

RFC: Decide what's the best testing framework to use w/in context of the open-next framework.

**Comment by khuezy** [comment]
Cool, sounds like a plan. I'll try to get something up by next week. Still need to figure how deploying would work (via SST would make sense but would need @fwang to set that up).

For the e2e integration, we should deploy: https://app-router.vercel.app/ and ensure all supported features are functional.

**Comment by conico974** [comment]
> Cool, sounds like a plan. I'll try to get something up by next week. Still need to figure how deploying would work (via SST would make sense but would need @fwang to set that up).
> 
> For the e2e integration, we should deploy: https://app-router.vercel.app/ and ensure all supported features are functional.

We might need to modify it, for a good e2e we need to have page dir in it too. 
In a perfect world we'd have 3 different app, app dir only, page dir only and page + app dir. And testing against different version of next might be useful too.

**Comment by khuezy** [comment]
In that case, we can use the `example` in here. Create 3 types of apps: `appDir` only, `pages` only, both. And deploy each as a subdomain: `https://app|pages|both.open-next.js.org/`

**Comment by devmanbr** [comment]
I think it's excellent. it's not sustainable to monitor compatibility every time next.js updates without automated testing.
