### ISSUE TITLE
`use client` doesn't work

### ISSUE THREAD

**Issue by fwang** [sst/open-next#127]
From @thomas-schmidt-fellowork:
https://github.com/serverless-stack/sst/issues/2840#issuecomment-1547840991

It also seems that new client components of next js 13 seem not to work. If i remove either "use client" or the Client import of sst it works again.

```
"use client";
import {Config} from "sst/node/config";
import {useState} from "react";

export default function Home() {

const [ok, setOk] = useState(true)

 return (
    <main>

        public var :  {Config.NEXT_PUBLIC_ANOTHER_VAR}
        <br></br>
        {ok}
    </main>
  )
}

```
Import trace for requested module:
./node_modules/aws-crt/dist/native/binding.js
./node_modules/aws-crt/dist/native/auth.js
./node_modules/aws-crt/dist/index.js
./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/is-crt-available.js
./node_modules/@aws-sdk/util-user-agent-node/dist-cjs/index.js
./node_modules/@aws-sdk/client-ssm/dist-cjs/runtimeConfig.js
./node_modules/@aws-sdk/client-ssm/dist-cjs/SSMClient.js
./node_modules/@aws-sdk/client-ssm/dist-cjs/index.js
./node_modules/sst/node/util/index.js
./node_modules/sst/node/config/index.js
./src/app/page.tsx
- warn Fast Refresh had to perform a full reload due to a runtime error.
- error Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by iduuck** [comment]
This has something to do with the Config not being Client compatible as it seems. Because simple `"use client"` is working for me [in my test](https://dridorbv8qzas.cloudfront.net/). In the test, I wrapped the logo in a `"use client"`.

**Comment by weisisheng** [comment]
Hit this as well, believe related to this open issue--> https://github.com/aws-amplify/amplify-js/issues/11030

[Module not found: Can't resolve 'aws-crt' when using API in nextjs@13.2](https://github.com/aws-amplify/amplify-js/issues/11030#top)

Horribly frustrating...

**Comment by jayair** [comment]
Can you post this on #open-next on Discord?

**Comment by khuezy** [comment]
Closing this per comment above.
