### ISSUE TITLE
basePath / assetPrefix is not respected in generated public-files.json

### ISSUE THREAD

**Issue by breningham** [sst/open-next#136]
basically, just what the title says. 

if you have a basePath or assetPrefix set in your next.config.js the generated public-files.json do not include said basePath or prefix.  

workaround is to manually modify the public-files.json to include said prefix. 

i can/am happy to create a PR to resolve this.

**Comment by breningham** [comment]
i'll get on it at some point today

**Comment by conico974** [comment]
`public-files.json` should not be used anymore
