### ISSUE TITLE
custom headers - middleware

### ISSUE THREAD

**Issue by cuquo** [sst/open-next#153]
With app router, the only way to share data with the root layout is by setting custom headers using middleware. 

With open next, those custom header can't be read from the layout via headers, with vercel this issues is not present.

layout
```ts
import { headers } from 'next/headers';

const RootLayout = (): JSX.Element => (
  <html lang="en">
    <body>
      {headers()}
      {props.children}
    </body>
  </html>
);
```

middleware
```ts
export async function middleware(request: NextRequest): Promise<NextResponse> {

  const response = NextResponse.next();
  response.headers.set('test', 'from middleware');

  return response;
}
```

**Comment by khuezy** [comment]
For now, the workaround is:
```typescript
import { NextResponse } from 'next/server'
 
// Given an incoming request...
const newHeaders = new Headers(request.headers)
// Add a new header
newHeaders.set('x-version', '123')
// And produce a response with the new headers
return NextResponse.next({
  request: {
    // New request headers
    headers: newHeaders,
  },
})
```

We'll want to add this to the docs and investigate a way to set the `x-middleware-...` stuff internally... see: https://github.com/vercel/next.js/blob/b4a875eb57fb396e236d2879e7afd821dc3c87a4/packages/next/src/server/web/spec-extension/response.ts#L25C18-L25C47
