### ISSUE TITLE
Lambda@Edge does not support environment variables.

### ISSUE THREAD

**Issue by LukaMacharashvili** [sst/open-next#157]
I'm trying deploy "server-function" on Lambda@Edge, but it turns out Lambda@Edge does not support environment variables. How am I supposed to configure some essential environment variables like CACHE_BUCKET_NAME, is there any workaround?

**Comment by khuezy** [comment]
NextjsSite environments at the edge. Did you try deploying?
https://github.com/serverless-stack/sst/blob/master/packages/sst/src/constructs/EdgeFunction.ts#L189
^ how it's done internally.
