### ISSUE TITLE
Next 13 Favicon file

### ISSUE THREAD

**Issue by mattkinnersley** [sst/open-next#158]
Next 13 allows you to create a `favicon.ico` file at `/app`. This will then automatically add a `<link>` to the head of the document for you. Docs [here](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons)

I have found that the favicon file is not included in the static assets folder of `.open-next` and is not being uploaded to the S3 bucket when using `npx sst deploy`.

**Comment by jayair** [comment]
Oh interesting. Can you post this in #open-next on Discord? We'll take a look.

**Comment by khuezy** [comment]
This is a Next quirk that hasn't been parity in open-next. You'll need to put your favicon.ico in `/public`

**Comment by khuezy** [comment]
@mattkinnersley would you be willing to implement this? I don't think open-next needs to do anything special. Nextjs should look at the icons stuff at the root `app` folder and do its magic. All `open-next` needs to do is to copy the icon to the `public` folder before it builds here: https://github.com/serverless-stack/open-next/blob/main/packages/open-next/src/build.ts#L54

**Comment by jayair** [comment]
@mattkinnersley want to take this on?

**Comment by mattkinnersley** [comment]
I will take a look at doing this next week 👍

**Comment by mattkinnersley** [comment]
Just about to take a look at this but looks like @annleefores beat me to it
