### ISSUE TITLE
Add ability to ignore files in the "public" directory

### ISSUE THREAD

**Issue by plevavas** [sst/open-next#165]
Hi,

First of all, thanks very much for this helpful project :)

I don't know if it's possible currently. I want to ignore some files in the "public" directory. There might be specific files or other configuration files that do not need to be included in the final build.

**Comment by khuezy** [comment]
Hi, I think this is more of a build or nextjs config request. For now, you'll need to write a pre or post build script to remove unwanted files/folder from the output.

**Comment by sladg** [comment]
I would argue that `There might be specific files or other configuration files that do not need to be included in the final build.` means these should not be committed or present in public folder a first place?

And ofc, easy workaround would be to remove them from `.open-next/assets` manually after build. Such as     `buildCommand: 'npx --yes open-next@2.1.1 build && 'rm .open-next/assets/favicon.ico,`

**Comment by plevavas** [comment]
Sounds good for me. I close the issue.
