### ISSUE TITLE
Next 13.4.13 broke modal interception

### ISSUE THREAD

**Issue by khuezy** [sst/open-next#168]
Originally, this was thought to be a nextjs bug b/c we reproduced it in standalone mode, but that was a false positive. The JS never ran b/c in standalone mode, you have to manually copy the static folder over, eg:
```
cd packages/web
npm run build
cd .next
cp -rf static standalone/packages/web/.next/static
```

repo: https://github.com/khuezy/sst-next-10

**Comment by khuezy** [comment]
cc @conico974

**Comment by khuezy** [comment]
Using the native `next/link` works... if you use a wrapper to trigger prefetch on hover, it breaks... I'll investigate and update here.

**Comment by khuezy** [comment]
The `Vary` header now contains `Accept-Encoding`, which shouldn't be there (forbidden header)
Vary: Accept-Encoding,RSC,Next-Router-State-Tree,Next-Router-Prefetch,Next-Url

The same site deployed to vercel does not contain the `Accept-Encoding` response headers. It also contains the full path of the route for its `next-url`, eg: `/route/to/page`, whereas open-next only has the root url: `/route`

**Comment by conico974** [comment]
I think i've found a solution, with the latest next.js they removed every routing element from next server (the one we use in open-next) and moved it to a router server https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/router-server.ts.
There is 2 way we could fix that: 
- We use render server https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/render-server.ts, but this mean we'd have cold start of more than 5-6 seconds at least for the simplest webpage. And we'd probably have to rewrite a lot of thing. But on the plus sides, this should fix all the require-hooks issue, or at least they will be on next sides
- We do the routing ourselves, but this will likely break in the future

Just for testing i added this function in server-adapter and my interception route is now working
```typescript

function handleRewrites(rawPath: string, headers: Record<string, string>) {
  const rewrite = routesManifest.rewrites.find(
    (route) =>
      new RegExp(route.regex).test(rawPath ?? '') &&
      route.has &&
      route.has.length > 0 &&
      route.has[0].type === 'header' &&
      route.has[0].key === 'Next-Url' &&
      new RegExp(route.has[0].value ?? '').test(headers?.['next-url'] ?? '')
  );
  return rewrite?.destination ?? rawPath;
}
```
And just changed the reqProps url here with the result https://github.com/serverless-stack/open-next/blob/274d446ed7e940cfbe7ce05a21108f4c854ee37a/packages/open-next/src/adapters/server-adapter.ts#L105 

I'll try to work on something today, i think that to make this works we need to handle rewrites and redirects. I'm not sure what will happen for earlier versions of next though.

**Comment by khuezy** [comment]
Awesome nice work! We now pass in x-open-next version I believe, maybe we can throw error for 2.0.6 if your next version is < 13.4.13
