### ISSUE TITLE
Deploy to other edge services

### ISSUE THREAD

**Issue by devmanbr** [sst/open-next#172]
Currently, you can only deploy what is intended for the edge environment on Lambda@Edge. Can you provide ways to deploy to other services to avoid lock-in? can you document?

**Comment by a-marcel** [comment]
You don't need to use lambda@edge. In a serverless AWS example, you can use Lambda via HTTP Endpoint. Described in that issue: https://github.com/sst/open-next/issues/32#issuecomment-1421831230

**Comment by conico974** [comment]
Everything needed should be in the docs for this with OpenNext V3
