### ISSUE TITLE
Codestyle guidelines

### ISSUE THREAD

**Issue by sladg** [sst/open-next#174]
👋 Looking at my experience as well as some other PRs (https://github.com/sst/open-next/pull/155/files) it would be wise to add Eslint config to the project to ensure we follow same formatting while developing.

**Comment by khuezy** [comment]
Ditto, I had to wrestle w/ my VSCode settings b/c there wasn't a lint config in this project.

**Comment by sladg** [comment]
@khuezy I'm gonna open PR for this, should be fairly simple, we just need to pick right setup for existing codebase 🚀
