### ISSUE TITLE
API routes return empty body on readable.pipe

### ISSUE THREAD

**Issue by Toshimichi0915** [sst/open-next#179]
## Environment

- Next.js 13.4.18
- SST 2.24.7

## Git Repository

https://github.com/Toshimichi0915/next-binary

## Details

When I create an api route that returns the body using Readable.pipe, the response body becomes empty. Here is the simplest example to demonstrate the error:

/src/pages/api/image.ts
```ts
import { NextApiRequest, NextApiResponse } from "next";
import { createReadStream } from "fs";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const file = createReadStream("./test.png");

  res.setHeader("Content-Type", "image/png");
  file.pipe(res);
}
```

OR

```ts
import { NextApiRequest, NextApiResponse } from "next";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const image = await fetch("https://toshimichi-public.s3.ap-northeast-1.amazonaws.com/icon.png")
  res.setHeader("Content-Type", "image/png");

  if (!image.body) {
    res.end()
    return
  }

  const reader = image.body.getReader()
  while (true) {
    const result = await reader.read()
    if (result.done) {
      res.end()
      return
    }

    res.write(result.value)
  }
}
```

/src/pages/index.tsx
```tsx
export default function Home() {
  return (
    <main>
      <h1>Hello, world!</h1>
      <img src="/api/image" alt="" />
    </main>
  );
}
```

## Expected result (localhost)

![image](https://github.com/sst/open-next/assets/26406334/4e2c7e2d-de04-4a86-85a9-38356bc76c8a)

## Actual result (AWS + SST)

https://d324kazraq8wun.cloudfront.net/
![image](https://github.com/sst/open-next/assets/26406334/1f34eb5c-cb13-4cf4-a742-fbf5fc4d7961)

![image](https://github.com/sst/open-next/assets/26406334/080948d6-7a94-4e3a-8a92-8e1d6a867d94)

## Temporary solution to this problem.

If you just want to upload images, you can buffer the contents of the image, and then use `response.write(buffer)` to display images.

```ts
export function readAll(readable: Readable): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const buffers: Buffer[] = [];

    readable.on("readable", () => {
      let chunk;
      while ((chunk = readable.read())) {
        buffers.push(chunk);
      }
    });
    readable.on("end", () => {
      resolve(Buffer.concat(buffers));
    });
    readable.on("error", (err) => {
      reject(err);
    });
  });
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  let buffer: Buffer;
  try {
    const reader = ...;
    buffer = await readAll(reader);
  } catch (e) {
    res.status(404).json({ message: "Not Found" });
    return;
  }

  res.setHeader("Content-Type", asset.mimeType);
  res.setHeader("Cache-Control", "public, max-age=31536000, immutable");
  res.write(buffer, "binary");
  res.end(null, "binary");
}
```

However, when working on non-image files, this method is also unreliable for some reasons. In fact, when I try to upload/download a zip file using this method, A zip file is always corrupted (This is yet to investigate).

**Comment by khuezy** [comment]
Hello, the streaming PR should allow you to stream data from the lambdas.

For this particular scenario though, you'd want to use `next/image` to load your images, as that will hit the image optimization lambda. Sladg also has a PR to allow streaming for the image opt lambda to further improve performance.

Also, you wouldn't want to upload images directly to your server b/c of the bandwidth consumption, you'd rather use a presigned url to upload to S3 directly to save your server from being a useless middle man.

**Comment by Toshimichi0915** [comment]
Thanks for reply.

I know image tag is better. I intentionally used img tag because it would be easier to debug and see what's going on.

I also don't use fs module for loading data in my website. In fact, I use s3 for my use case. However, as this is just an example, I decided to use fs module for simplicity in this case.

**Comment by khuezy** [comment]
Look at your cloudwatch logs, there might be an error in loading the images. The images don't get bundle in the lambda code, so I think your example isn't that the pipe isn't sending data to the client, it's the in the lambda env, the image doesn't exist.

**Comment by khuezy** [comment]
Did you make the appropriate changes to the NextjsSite side? You have to change the type to stream

**Comment by khuezy** [comment]
I've confirmed that sending the stream works:
`const file = createReadStream("./test.png");`

change to:
`const file = createReadStream(path.join(process.cwd(), "/pages/api/test.png");`

You might need to add "/src" to that path (or maybe not). But if you have some images in `/public`, you can just do `createReadStream(path.join(process.cwd(), "/public/test.png");`

**Comment by Toshimichi0915** [comment]
Oops, I didn't realize there are 2 PRs to support streaming in AWS lambda, and I was using the one in draft mode the whole time, instead of what you are talking about.

https://github.com/sst/open-next/pull/175
https://github.com/sst/open-next/pull/170

Well, completely unrelated, but I believe instead of just streaming images, everything should be streamed, including binary files like zip and tar.

https://github.com/sst/open-next/blob/main/packages/open-next/src/adapters/binary.ts#L4-#L56

This list is completely incomplete, and that causes binary files to be corrupted. For example, `x-zip-compressed` is not listed here.

**Comment by conico974** [comment]
Fixed in [V3](https://github.com/sst/open-next/releases/tag/v3.0.0)
