### ISSUE TITLE
Next.js app router

### ISSUE THREAD

**Issue by valerarusu7** [sst/open-next#182]
Will there be an example on how to use this with the new `app` directory?

**Comment by khuezy** [comment]
You can check the nextjs example for reference, it's not open-next dependent. Having said that, check out the end-to-end test PR, it has a basic project: https://github.com/sst/open-next/pull/178/files#diff-424d6b2cbf402c1bda2aec8c13c88514d1444156b932c4d50aabf529f656d00a

**Comment by valerarusu7** [comment]
> You can check the nextjs example for reference, it's agnostic of any platform. Having said that, check out the end-to-end test PR, it has a basic project: https://github.com/sst/open-next/pull/178/files#diff-424d6b2cbf402c1bda2aec8c13c88514d1444156b932c4d50aabf529f656d00a

Thank you
