### ISSUE TITLE
Project codebase improvements

### ISSUE THREAD

**Issue by sladg** [sst/open-next#184]
I have noticed couple of things which are not sub-optimal and messes up developer experience when working on project.

1. Use of Plain JS in example site. Considering SST is written mostly in TS as well as open-next, I would expect even tests and examples being done in same way.
2. `packages/open-next/assets` contains copy-pasted `node_modules` for Image optimisation Lambda. These shouldn't be part of repository, but should be dealt with in more reasonable way, such as: zip file, lambda layer, minified dist file, or similar.
3. No automated tests or deployments are in place. Considering we already have example site with lot of cases identified by @fwang. It would make sense to setup automated testing so any PR gets bundled, deployed and tested. This could also include daily tests for specific Next versions so we can ensure compatibility with wide-range of projects. Considering the serverless nature of open-next, I should be rather straight forward to achieve.
4. We are relying on `tsc` to build files for this package. Uses `tsup` is generally best case practise as it allows for extra configuration such as multiple inputs, bundling and minifying the output.

**Comment by jayair** [comment]
Thanks! Just to double check, you are in our Discord right?

**Comment by sladg** [comment]
Additional thing we came across in regards to streaming.

Current copy of `serverless-http`'s `response` is rather finicky. We might want to clean it up properly and provide easy commands to call from our wrapper.

**Comment by sladg** [comment]
Might be worth investigating https://github.com/awslabs/aws-lambda-web-adapter and trying to use it as translation layer between event and HTTP. It's as first-party as we can get.

**Comment by conico974** [comment]
I consider this one mostly done. 
Feel free to reopen it if needed
