### ISSUE TITLE
Problems with ISR and latest Next version

### ISSUE THREAD

**Issue by marcantoineveilleux** [sst/open-next#197]
#### Issue Description:

I am experiencing an issue with Next.js version `13.4.19` where I consistently encounter a `Failed to load static props` error while navigating to a page that utilizes `getStaticPaths` and `getStaticProps`. Here is the return code snippet for `getStaticPaths` (i am using ISR):

```javascript
{
  paths: [],
  fallback: true,
}
```

#### Additional Context:

- For a separate issue, I had to employ [a workaround](https://github.com/vercel/next.js/issues/49169#issuecomment-1644272017) to address problems related to `__NEXT_PRIVATE_PREBUNDLED_REACT`.
  
- I am using the conventional pages-based routing structure and not the new app directory feature.

#### Workarounds:

1. When I disable the fallback option in `getStaticPaths`, the error is resolved.
2. Downgrading to Next.js version `13.4.12` also resolves the issue.

#### Logs:

I am relatively new to SST/Open-Next and couldn't find any relevant logs in AWS CloudWatch to help diagnose the issue.

**Comment by khuezy** [comment]
@marcantoineveilleux Please test using `open-next@0.0.0-20230902021344` rc

**Comment by marcantoineveilleux** [comment]
@khuezy Works for me, thanks!
