### ISSUE TITLE
Do you have example Terraform, CloudFormation, SDK, or other infrastructure examples?

### ISSUE THREAD

**Issue by Gregory-Ledray** [sst/open-next#22]
Hi. Do you have example Terraform, CloudFormation, SDK, or other infrastructure examples? Although I can build my own, I'd prefer to start with an example template.

**Comment by fwang** [comment]
Hey @Gregory-Ledray, I will share some examples shortly. Will keep you posted here.

**Comment by mhaslam-becklar** [comment]
That would be excellent! I would particularly be interested in a Terraform example.

Thanks for all the hard work on this awesome project, @fwang!

**Comment by taymoork2** [comment]
@fwang with SST2 out and it's examples still being AWS heavy, the need for other infra templating examples is much needed, especially for those with enterprise setups that aren't using AWS or on-prem solutions.

**Comment by taymoork2** [comment]
There's not enough documentation at the moment that explains how to use the SSG generated files in the `.next` folder along with `.open-next` build assets

**Comment by devmanbr** [comment]
I'm kinda newbie, and really some examples would help a lot (especially using terraform, which is my main need).

thank you so much for this amazing project!

**Comment by brett-james-rocketlab** [comment]
Also would like examples for SSG too!

**Comment by mark-strudwick** [comment]
I +1 this, it would be nice to include some examples using CFN, CDK, or TF. SST2 looks cool, but it deploys a bunch of resources that are unnecessary when the project only requires the basic resources to run open-next

**Comment by Sreejit7** [comment]
+1 for a much-needed Terraform example! Would love to try out open-next which will finally allow us to upgrade our codebases to Next.js 13!

**Comment by jayair** [comment]
Mischa released one for CDK that uses OpenNext: https://github.com/jetbridge/cdk-nextjs

**Comment by RJPearson94** [comment]
hey all, 

For anyone interested, I have been developing a Terrraform module that will deploy a Open Next app to AWS. It can be found at https://github.com/RJPearson94/terraform-aws-open-next and in the Terraform Registry.

Examples of how the module can be used can be found at https://github.com/RJPearson94/terraform-aws-open-next-examples

Hope it helps. Any feedback is welcome. Please raise an issue on the corresponding repo

**Comment by fwang** [comment]
Hey @RJPearson94, this is awesome! Will add to the README.

**Comment by benkraus** [comment]
Also throwing out there that I stumbled upon this: https://github.com/nhs-england-tools/terraform-aws-opennext
