### ISSUE TITLE
Middleware cookies are not being applied to response

### ISSUE THREAD

**Issue by ldlinhlxag** [sst/open-next#224]
Hi @khuezy ,
After open-next update #208, our production on AWS is more stable.
However, it has a bug with next-intl, specifically:
If we use the URL in the browser: http://PROD_URL/, it will cause an error and the page will not render.
However, if we use the URL: http://PROD_URL/en/, it will return the home page.
I also tried using yarn open:build and yarn start locally, which works fine.
The difference between production and locally is that:
In the local cookie, there is a value of NEXT_LOCALE = en, but the production environment does not find this cookie.

![image](https://github.com/sst/open-next/assets/70180964/e31e2d8a-991f-4511-b5b3-c7b7e2f97a9b)

I used:
nextjs : 13.4.13
next-intl: 2.20.0
next-auth: ^4.22.1
Source: https://github.com/amannn/next-intl/tree/main/examples/example-next-13-next-auth

**Comment by khuezy** [comment]
hi @ldlinhlxag thanks for the report. I'm not familiar w/ next-intl, I'll take a look on Monday. Are you setting that cookie or does that library manage that.

**Comment by ldlinhlxag** [comment]
Hi @khuezy ,
The library managed that cookie. 
All configurations in middleware.

**Comment by khuezy** [comment]
@ldlinhlxag Please test out https://github.com/sst/open-next/releases/tag/v2.1.3
The cookies set in middleware should not be properly set in the response.

**Comment by ldlinhlxag** [comment]
Hi @khuezy,
I used 2.1.3 version.
It still doesn't have NEXT_LOCAL in cookies.
Now both http://PROD_URL/ and http://PROD_URL/en/ don't work.
And there is 1 more error in the log:

![image](https://github.com/sst/open-next/assets/70180964/705d329c-8d36-49d5-ba67-4e8979242bd0)

**Comment by khuezy** [comment]
Hmm that's strange, can you put up a min repo?
This was the change in 2.1.3: https://github.com/sst/open-next/pull/227/files
I don't know how that would cause that issue... the error message is very cryptic.

**Comment by khuezy** [comment]
Does that cookie have an "Expires=" by chance?

**Comment by ldlinhlxag** [comment]
This is cookies in my local:
![image](https://github.com/sst/open-next/assets/70180964/879f7b96-9a59-42a0-a19d-af3feebf69ad)

**Comment by khuezy** [comment]
Ah, it does have an expires in, I have a fix that was merged (but the e2e tests failed for an unrelated reason)
https://github.com/sst/open-next/pull/230
I'll get 2.1.4 out for this.

**Comment by khuezy** [comment]
@ldlinhlxag can you try 2.1.4, it should fix the parsing of the cookies... if it doesn't work, can you share a min repo w/ your `sst` config.

**Comment by ldlinhlxag** [comment]
Hi @khuezy ,
Sorry for delay response.
I used custom headers and redirect in next.config.js. Maybe it causes impact here.
After I removed custom headers and redirect in next.config.js, it works but cannot switch lang multiple times.
Eg: http://PROD_URL/en -> http://PROD_URL/de (OK) ->  http://PROD_URL/en (Failed, and freeze with de)
I'm trying gather more value information.
I used terraform to deploy. 
This will upload server-function to AWS Lambda, static asset to S3 and configure CloudFront.
If you interested in specific area of terraform, just tell me.
I cannot show you entire infra terraform (policy security).

**Comment by khuezy** [comment]
Look at the example here: https://github.com/sst/open-next/blob/main/examples/app-router/middleware.ts#L41-L51

```
const r = NextResponse.next({
    headers: responseHeaders, // these headers get sent back to the client
    request: {
      headers: requestHeaders, // these headers goes to the next request
    },
  });
```

**Comment by ldlinhlxag** [comment]
Yes, let me try it!

**Comment by ldlinhlxag** [comment]
Hi @khuezy ,
I gather details log for this issue:

At first time:
Access URL: https://PROD_URL/login -> (OK)

`
Before middleware cookie: undefined
Middleware response:
{
  cookies: ResponseCookies {"NEXT_LOCALE":{"name":"NEXT_LOCALE","value":"en","sameSite":"strict","maxAge":31536000,"expires":"2024-09-14T00:22:14.698Z","path":"/"}},
  url: '',
  body: null,
  bodyUsed: false,
  headers: {
  link: '<https://PROD_URL/login>; rel="alternate"; hreflang="en", <https://PROD_URL/de/login>; rel="alternate"; hreflang="de", <https://PROD_URL/login>; rel="alternate"; hreflang="x-default"',
  set-cookie: 'NEXT_LOCALE=en; Path=/; Expires=Sat, 14 Sep 2024 00:22:14 GMT; Max-Age=31536000; SameSite=strict',
  x-middleware-rewrite: 'https://PROD_URL/en/login'
},
  ok: true,
  redirected: false,
  status: 200,
  statusText: '',
  type: 'default'
}

Open-next response:

2023-09-15T00:22:15.635Z	7190d699-c5a2-4a8c-8b26-40740776955e	INFO	ServerResponse data {
  statusCode: 200,
  headers: [Object: null prototype] {
    vary: 'RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Url',
    'x-powered-by': 'Next.js',
    'cache-control': 'private, no-cache, no-store, max-age=0, must-revalidate',
    'content-type': 'text/html; charset=utf-8',
    link: '<https://PROD_URL/login>; rel="alternate"; hreflang="en", <https://PROD_URL/de/login>; rel="alternate"; hreflang="de", <https://PROD_URL/login>; rel="alternate"; hreflang="x-default"',
    'set-cookie': 'NEXT_LOCALE=en; Path=/; Expires=Sat, 14 Sep 2024 00:22:14 GMT; Max-Age=31536000; SameSite=strict',
    'x-middleware-rewrite': 'https://PROD_URL/en/login'
  },
  isBase64Encoded: false,
  ...
}
`

At second time: en -> de -> (OK)
Access URL: https://PROD_URL/de/login

`
Before middleware cookie: { name: 'NEXT_LOCALE', value: 'en' }
Middleware response:

2023-09-15T00:26:28.328Z	213da1ab-ec9e-4e3d-ab7b-4843589b72eb	INFO	Response detail: {
  cookies: ResponseCookies {"NEXT_LOCALE":{"name":"NEXT_LOCALE","value":"de","sameSite":"strict","maxAge":31536000,"expires":"2024-09-14T00:26:28.327Z","path":"/"}},
  url: '',
  body: null,
  bodyUsed: false,
  headers: {
  link: '<https://PROD_URL/login>; rel="alternate"; hreflang="en", <https://PROD_URL/de/login>; rel="alternate"; hreflang="de", <https://PROD_URL/login>; rel="alternate"; hreflang="x-default"',
  set-cookie: 'NEXT_LOCALE=de; Path=/; Expires=Sat, 14 Sep 2024 00:26:28 GMT; Max-Age=31536000; SameSite=strict',
},
  ok: true,
  redirected: false,
  status: 200,
  statusText: '',
  type: 'default'
}

Open-next response:

2023-09-15T00:26:28.426Z	213da1ab-ec9e-4e3d-ab7b-4843589b72eb	INFO	ServerResponse data {
  statusCode: 200,
  headers: [Object: null prototype] {
    vary: 'RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Url',
    'x-powered-by': 'Next.js',
    'cache-control': 'private, no-cache, no-store, max-age=0, must-revalidate',
    'content-type': 'text/html; charset=utf-8',
    link: '<https://PROD_URL/login>; rel="alternate"; hreflang="en", <https://PROD_URL/de/login>; rel="alternate"; hreflang="de", <https://PROD_URL/login>; rel="alternate"; hreflang="x-default"',
    'set-cookie': 'NEXT_LOCALE=de; Path=/; Expires=Sat, 14 Sep 2024 00:26:28 GMT; Max-Age=31536000; SameSite=strict',
    'x-middleware-next': '1'
  },
  isBase64Encoded: false,
}
`

At third time: de -> en -> (Failed)
Access URL: https://PROD_URL/en/login
`
Before middleware cookie: { name: 'NEXT_LOCALE', value: 'de' }
Middleware response:

2023-09-15T00:28:24.398Z	5a6097d9-c1d9-4236-8231-33e0aa02f07f	INFO	Response detail: {
  cookies: ResponseCookies {"NEXT_LOCALE":{"name":"NEXT_LOCALE","value":"en","sameSite":"strict","maxAge":31536000,"expires":"2024-09-14T00:28:24.397Z","path":"/"}},
  url: '',
  body: null,
  bodyUsed: false,
  headers: {
  link: '<https://PROD_URL/login>; rel="alternate"; hreflang="en", <https://PROD_URL/de/login>; rel="alternate"; hreflang="de", <https://PROD_URL/login>; rel="alternate"; hreflang="x-default"',
  location: 'https://PROD_URL/login',
  set-cookie: 'NEXT_LOCALE=en; Path=/; Expires=Sat, 14 Sep 2024 00:28:24 GMT; Max-Age=31536000; SameSite=strict'
},
  ok: false,
  redirected: false,
  status: 307,
  statusText: '',
  type: 'default'
}

Open-next response:

2023-09-15T00:28:25.983Z	deae3a98-af55-46f7-af52-71f6e7bb4d9f	INFO	ServerResponse data {
  statusCode: 200,
  headers: [Object: null prototype] {
    vary: 'RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Url',
    'x-powered-by': 'Next.js',
    'cache-control': 'private, no-cache, no-store, max-age=0, must-revalidate',
    'content-type': 'text/html; charset=utf-8',
    link: '<https://PROD_URL/login>; rel="alternate"; hreflang="en", <https://PROD_URL/de/login>; rel="alternate"; hreflang="de", <https://PROD_URL/login>; rel="alternate"; hreflang="x-default"',
    'x-middleware-next': '1'
  },
  isBase64Encoded: false,
}
`
If you need more information, just tell me.

**Comment by khuezy** [comment]
@ldlinhlxag I saw a comment in my email but I don't see it here on GitHub, did you delete? Can you join the SST discord and create a help thread? It'll be easier to communicate.

**Comment by ldlinhlxag** [comment]
Hi @khuezy ,
I gather detail logs:

**At first time:
Access URL: https://PROD_URL/login**

**Before middleware cookie: undefined**

**Middleware response:**

```
{
  cookies: ResponseCookies {"NEXT_LOCALE":{"name":"NEXT_LOCALE","value":"en","sameSite":"strict","maxAge":31536000,"expires":"2024-09-14T00:22:14.698Z","path":"/"}},
  url: '',
  body: null,
  bodyUsed: false,
  headers: {
  link: '<https://PROD_URL/login>; rel="alternate"; hreflang="en", <https://PROD_URL/de/login>; rel="alternate"; hreflang="de", <https://PROD_URL/login>; rel="alternate"; hreflang="x-default"',
  set-cookie: 'NEXT_LOCALE=en; Path=/; Expires=Sat, 14 Sep 2024 00:22:14 GMT; Max-Age=31536000; SameSite=strict',
  x-middleware-rewrite: 'https://PROD_URL/en/login'
},
  ok: true,
  redirected: false,
  status: 200,
  statusText: '',
  type: 'default'
}
```

**Open-next response:**

```
2023-09-15T00:22:15.635Z	7190d699-c5a2-4a8c-8b26-40740776955e	INFO	ServerResponse data {
  statusCode: 200,
  headers: [Object: null prototype] {
    vary: 'RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Url',
    'x-powered-by': 'Next.js',
    'cache-control': 'private, no-cache, no-store, max-age=0, must-revalidate',
    'content-type': 'text/html; charset=utf-8',
    link: '<https://PROD_URL/login>; rel="alternate"; hreflang="en", <https://PROD_URL/de/login>; rel="alternate"; hreflang="de", <https://PROD_URL/login>; rel="alternate"; hreflang="x-default"',
    'set-cookie': 'NEXT_LOCALE=en; Path=/; Expires=Sat, 14 Sep 2024 00:22:14 GMT; Max-Age=31536000; SameSite=strict',
    'x-middleware-rewrite': 'https://PROD_URL/en/login'
  },
  isBase64Encoded: false,
  ...
}
```

**At second time: en -> de
Access URL: https://PROD_URL/de/login**

**Before middleware cookie: { name: 'NEXT_LOCALE', value: 'en' }**

**Middleware response:**

```
2023-09-15T00:26:28.328Z	213da1ab-ec9e-4e3d-ab7b-4843589b72eb	INFO	Response detail: {
  cookies: ResponseCookies {"NEXT_LOCALE":{"name":"NEXT_LOCALE","value":"de","sameSite":"strict","maxAge":31536000,"expires":"2024-09-14T00:26:28.327Z","path":"/"}},
  url: '',
  body: null,
  bodyUsed: false,
  headers: {
  link: '<https://PROD_URL/login>; rel="alternate"; hreflang="en", <https://PROD_URL/de/login>; rel="alternate"; hreflang="de", <https://PROD_URL/login>; rel="alternate"; hreflang="x-default"',
  set-cookie: 'NEXT_LOCALE=de; Path=/; Expires=Sat, 14 Sep 2024 00:26:28 GMT; Max-Age=31536000; SameSite=strict',
},
  ok: true,
  redirected: false,
  status: 200,
  statusText: '',
  type: 'default'
}
```

**Open-next response:**

```
2023-09-15T00:26:28.426Z	213da1ab-ec9e-4e3d-ab7b-4843589b72eb	INFO	ServerResponse data {
  statusCode: 200,
  headers: [Object: null prototype] {
    vary: 'RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Url',
    'x-powered-by': 'Next.js',
    'cache-control': 'private, no-cache, no-store, max-age=0, must-revalidate',
    'content-type': 'text/html; charset=utf-8',
    link: '<https://PROD_URL/login>; rel="alternate"; hreflang="en", <https://PROD_URL/de/login>; rel="alternate"; hreflang="de", <https://PROD_URL/login>; rel="alternate"; hreflang="x-default"',
    'set-cookie': 'NEXT_LOCALE=de; Path=/; Expires=Sat, 14 Sep 2024 00:26:28 GMT; Max-Age=31536000; SameSite=strict',
    'x-middleware-next': '1'
  },
  isBase64Encoded: false,
}
```

**At third time: de -> en
Access URL: https://PROD_URL/en/login**

**Before middleware cookie: { name: 'NEXT_LOCALE', value: 'de' }**

**Middleware response:**

```
2023-09-15T00:28:24.398Z	5a6097d9-c1d9-4236-8231-33e0aa02f07f	INFO	Response detail: {
  cookies: ResponseCookies {"NEXT_LOCALE":{"name":"NEXT_LOCALE","value":"en","sameSite":"strict","maxAge":31536000,"expires":"2024-09-14T00:28:24.397Z","path":"/"}},
  url: '',
  body: null,
  bodyUsed: false,
  headers: {
  link: '<https://PROD_URL/login>; rel="alternate"; hreflang="en", <https://PROD_URL/de/login>; rel="alternate"; hreflang="de", <https://PROD_URL/login>; rel="alternate"; hreflang="x-default"',
  location: 'https://PROD_URL/login',
  set-cookie: 'NEXT_LOCALE=en; Path=/; Expires=Sat, 14 Sep 2024 00:28:24 GMT; Max-Age=31536000; SameSite=strict'
},
  ok: false,
  redirected: false,
  status: 307,
  statusText: '',
  type: 'default'
}
```

**Open-next response:**

```
2023-09-15T00:28:25.983Z	deae3a98-af55-46f7-af52-71f6e7bb4d9f	INFO	ServerResponse data {
  statusCode: 200,
  headers: [Object: null prototype] {
    vary: 'RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Url',
    'x-powered-by': 'Next.js',
    'cache-control': 'private, no-cache, no-store, max-age=0, must-revalidate',
    'content-type': 'text/html; charset=utf-8',
    link: '<https://PROD_URL/login>; rel="alternate"; hreflang="en", <https://PROD_URL/de/login>; rel="alternate"; hreflang="de", <https://PROD_URL/login>; rel="alternate"; hreflang="x-default"',
    'x-middleware-next': '1'
  },
  isBase64Encoded: false,
}
```
Yes, I will join later.
