### ISSUE TITLE
Windows Issues

### ISSUE THREAD

**Issue by khuezy** [sst/open-next#241]
Some users are reporting build issues on their Window machine (God bless them.)

As a starter, we should add a windows matrix to our test to ensure it build properly on windows.

**Comment by olivergrimes** [comment]
I've run into issues with this, it might even be worth just adding a note in the docs to highlight there are issues with windows?

**Comment by fwang** [comment]
Linking to a few Discord threads of windows related issues:
- https://discord.com/channels/983865673656705025/1198952519490076732/1199473418748301352
- https://discord.com/channels/983865673656705025/1192564590396067980/1192781953276067840
- https://discord.com/channels/983865673656705025/1192564590396067980/1192778355339182140

**Comment by khuezy** [comment]
I've seen 1 or 2 windows related path issue get resolved on next, is this still a problem?

**Comment by conico974** [comment]
I didn't see this one, let's keep only one open, i've already pinned https://github.com/sst/open-next/issues/385
