### ISSUE TITLE
Allow specification of which `sharp` version to use.

### ISSUE THREAD

**Issue by mkossoris** [sst/open-next#243]
I'd like to use `open-next` for my job, but we have an internal NPM registry with only specific versions of packages available based on auto-scanning. Unfortunately, the version of `sharp` currently hard-coded in the install command of the image optimization build function (0.32.5) is, at least right now, blocked. It might make more sense to make `sharp` a peer dependency or to add to the build interface allowing us to specify which version of `sharp` to use.

This is the build command I'm referring to: https://github.com/sst/open-next/blob/main/packages/open-next/src/build.ts#L327

**Comment by khuezy** [comment]
Good idea, do you think you can put up a PR?

**Comment by mkossoris** [comment]
Yeah I can look into it this week!

**Comment by lasley** [comment]
Ran across this need on my end as well, and submitted #259 (which works well for me). Thanks for the pointer on where exactly needed to be changed @mkossoris

**Comment by mkossoris** [comment]
@lasley thanks for taking this! I ended up getting super busy and was going to take a look this week but was pleasantly surprised to see you'd already done it haha.
