### ISSUE TITLE
Add support for automatic framework environment variables

### ISSUE THREAD

**Issue by juaoose** [sst/open-next#247]
I currently use `NEXT_PUBLIC_VERCEL_URL` for an integration with Cognito (I need the base URL on the client side for the redirect URLs), it would be nice if OpenNext would make this (and maybe a few [these](https://vercel.com/docs/projects/environment-variables/system-environment-variables)) variables available on deploy

I think the current workaround is to deploy the SST stack and then manually add such environment variable?

**Comment by khuezy** [comment]
Normally, you'd need to know what your site is, eg: `example.com`. So you'd just put that in the NextjsSite environment variable.
