### ISSUE TITLE
Use `globalThis` instead of `process.env` to pass build-time value to run-time

### ISSUE THREAD

**Issue by fwang** [sst/open-next#264]
We use `globalThis` to pass `disableIncrementalCache` and `disableDynamoDBCache` to runtime.
https://github.com/sst/open-next/blob/1ce30f6289b43d803aefa51b6a860c8af1b9e65e/packages/open-next/src/build.ts#L745-L751

And we use `process.env` to pass `OPEN_NEXT_DEBUG` and `OPEN_NEXT_VERSION` to runtime.
https://github.com/sst/open-next/blob/1ce30f6289b43d803aefa51b6a860c8af1b9e65e/packages/open-next/src/build.ts#L769-L775

Let's use one. `globalThis` feels to be the more correct approach?

**Comment by conico974** [comment]
Yeah it makes sense to use only one, and in this case `globalThis` seems to be the more appropriate.

**Comment by fwang** [comment]
Switched to using `globalThis` everywhere.
