### ISSUE TITLE
Remove temporary `getDerivedTags` value

### ISSUE THREAD

**Issue by fwang** [sst/open-next#266]
Noticed the import `getDerivedTags` line was commented out. Just double checking if this is the expected behavior.
https://github.com/sst/open-next/blob/1ce30f6289b43d803aefa51b6a860c8af1b9e65e/packages/open-next/src/adapters/cache.ts#L16-L22

**Comment by conico974** [comment]
Yes that's expected, i just forgot to remove it. 
It was used before next@13.5.1 but is no longer useful since they changed the way it is done. And since `next/cache` requires 13.5.1 to work properly for us, we could just remove this

**Comment by fwang** [comment]
Removed.

**Comment by fwang** [comment]
Just confirming, we can remove the `getDerivedTags()` function completely right? As it is just returning whatever is passed in.

**Comment by conico974** [comment]
Yeah, you can remove it safely
