### ISSUE TITLE
Static references to package.json does not support Monorepos

### ISSUE THREAD

**Issue by iDVB** [sst/open-next#296]
This reference to the nextJS version does not support monorepos
https://github.com/sst/open-next/blob/24c5166377346bed1a029fb2223cf7f3b52a10d3/packages/open-next/src/build.ts#L899

Perhaps a better way to find out this version is to ....

Use require.resolve to get the path to the Next.js package, and then derive its package.json location. This way you don't have to make assumptions about its location in a monorepo or other complex setups.
```
function getNextVersion() {
  const nextPath = require.resolve('next/package.json');
  const version = require(nextPath).version;

  console.log('Start of getNextVersion function')
  return version.split('-')[0];
}
```

**Comment by khuezy** [comment]
Sure that'll be great. FWIW, I'm using a monorepo setup and that works. What setup are you using? Is it nx?

**Comment by khuezy** [comment]
What if your monorepo contains 2 nextjs app w/ different versions. How would `require.resolve`... resolve the right version?

**Comment by iDVB** [comment]
It matters only which version the app resolves to. in that case its going to resolve to whichever version the package management resolves to for the developer. 🍎 2 🍎 , in my understanding.

**Comment by khuezy** [comment]
K, feel free to open a PR, we'll get it in the next release (there's ~3 PRs)

**Comment by iDVB** [comment]
hmmm... looking into this further.... it looks like this issue was addressed in the [findNextPackageJsonPath function](https://github.com/sst/open-next/blob/24c5166377346bed1a029fb2223cf7f3b52a10d3/packages/open-next/src/build.ts#L173)... but not the [getNextVersion function](https://github.com/sst/open-next/blob/24c5166377346bed1a029fb2223cf7f3b52a10d3/packages/open-next/src/build.ts#L895).... and I think both maybe could use this same method? but now I'm out of my depth on what [nextPackageJsonPath](https://github.com/sst/open-next/blob/24c5166377346bed1a029fb2223cf7f3b52a10d3/packages/open-next/src/build.ts#L122) is used for.

**Comment by khuezy** [comment]
```
  const appPath = path.join(process.cwd(), opts.appPath || "."); // `appPath` was added for monorepos like nx
  const buildOutputPath = path.join(process.cwd(), opts.buildOutputPath || ".");
  const outputDir = path.join(buildOutputPath, ".open-next");
  const nextPackageJsonPath = findNextPackageJsonPath(appPath, root); // this grabs the next's package.json path
  return {
    openNextVersion: getOpenNextVersion(),
    nextVersion: getNextVersion(nextPackageJsonPath), // we pass in the next's package here to find out what version it is
```

**Comment by GlisboaDev** [comment]
I was having the same issue, and opened a PR addressing it. These changes allows me to run it on my nx workspace, but let me know if any thoughts there.

**Comment by conico974** [comment]
Should be fixed in https://github.com/sst/open-next/pull/322
Feel free to reopen the issue if this is still an issue
