### ISSUE TITLE
Issue using apps directory

### ISSUE THREAD

**Issue by ziggy6792** [sst/open-next#328]
Hi firstly thanks so much for this!

I had a lot of success deploying this using next 13 and the old pages directory but not the new apps directory.

When I use the new apps directory my deployed site just returns null
https://dvy374fpkcsdt.cloudfront.net/
![Screenshot 2023-12-04 at 1 44 17 AM](https://github.com/sst/open-next/assets/60313838/37a48d86-ee5a-4a1c-b647-979c3cbcd23b)
Example branch here https://github.com/ziggy6792/typescript-journey/tree/apps-directory
It is very hard to debug. I see no issues in the server lambda or in the browser console.

But using the old next JS pages directory everything works fine
Example branch here https://github.com/ziggy6792/typescript-journey/tree/pages-directory

FYI both sample next apps above were simply created from t3 https://create.t3.gg/ just with 
`EXPERIMENTAL  Would you like to use Next.js App Router?` on or off

I thought maybe apps directory is not supported yet. But it says here that it is https://open-next.js.org/

Any help would be very very much appreciated. 

Thanks,

**Comment by ziggy6792** [comment]
Hey, do you mean the cloudwatch logs for the lambda server function? 
There are none

Thanks :)

**Comment by khuezy** [comment]
There should be logs somewhere in the log groups. Trying using: https://docs.sst.dev/constructs/NextjsSite#logging

**Comment by khuezy** [comment]
You shouldn't need to set `buildCommand` unless you have a specific need for it. Most of the props (except minify) are exposed via `NextjsSite`
