### ISSUE TITLE
ServerFunction Lambda is importing modules that are only used in getStaticProps

### ISSUE THREAD

**Issue by pancho111203** [sst/open-next#33]
I'm migrating an existing project that uses mainly getStaticProps for data fetching. In Vercel, the code inside getStaticProps only runs during build, and the lambda functions only import and store their dependencies. However, using open-next with sst, my lambda function is failing due to trying to run some code that should only be imported during build (inside getStaticProps).

**Comment by conico974** [comment]
Feel free to reopen if you still have issues
