### ISSUE TITLE
Incorrect x-prerender-revalidate value breaks on-demand revalidation

### ISSUE THREAD

**Issue by grefrit** [sst/open-next#333]
Try to make HEAD request to page with incorrect x-prerender-revalidate value, it will cause CF cache this request (HIT). After that, even if you try to revalidate page with correct x-prerender-revalidate value, it will not reach lambda function, and will be HIT by CF. It's a security vulnerability that allows anybody to break you on-demand revalidation and you will have to manually invalidate CF cache and after that revalidate this page.

Step-by-step:
Make HEAD request with correct x-prerender-revalidate value to desired page, you will see x-nextjs-cache REVALIDATED header in the response

Make HEAD request with incorrect x-prerender-revalidate value to this page, you will see x-nextjs-cache HIT header in the response

Try again to make HEAD request with correct x-prerender-revalidate value, instead of REVALIDATED you will see HIT and your page will not be revalidated (because actually it will never reach lambda function)

**Comment by conico974** [comment]
Not an issue in open-next, it's been fixed in sst in https://github.com/sst/sst/pull/3713
