### ISSUE TITLE
Next Js 14 changes the custom cache handler path

### ISSUE THREAD

**Issue by Manuel-Antunes** [sst/open-next#354]
# Description

The current Nextjs version turns the cache handlers stable, so the old property `experimental.incrementalCacheHandlerPath` don't enables the s3/dynamo cache handler

# Proposed Changes
* create a behavior for next14 applications to redirect the property `experimental.incrementalCacheHandlerPath` to `cacheHandler`

**Comment by conico974** [comment]
You can downgrade to `next@14.0.4` for now, this was introduced in `14.1`
I'll try to create a PR later today or tomorrow.

**Comment by Manuel-Antunes** [comment]
https://github.com/sst/open-next/pull/356

**Comment by conico974** [comment]
Fixed in #356
