### ISSUE TITLE
CommonJS server function

### ISSUE THREAD

**Issue by r34son** [sst/open-next#367]
Can i somehow have my handler be bundled in commonjs format?

**Comment by r34son** [comment]
@khuezy @conico974 Could you help me please?

**Comment by r34son** [comment]
I guess i can patch here https://github.com/sst/open-next/blob/3deb2022d0bb506e4c4b66baeae248c7c2b153e5/packages/open-next/src/build.ts#L913
And maybe rewrite some banners in cjs

**Comment by conico974** [comment]
It might work, but that's likely not something that we'll merge in the repo.
And it will never work in V3 since we need top level await there for core functionality. 
What's your usecase for this?

**Comment by r34son** [comment]
Oh, i`m trying to deploy sls function to the Yandex Cloud. They do not support esm yet.
https://cloud.yandex.ru/en/docs/functions/lang/nodejs/handler

**Comment by r34son** [comment]
@conico974 Can you please suggest, why next is external [here](https://github.com/sst/open-next/blob/3deb2022d0bb506e4c4b66baeae248c7c2b153e5/packages/open-next/src/build.ts#L722)? Can i bundle it and upload only `index.mjs` without need to install packages and archive them. My usecase that I use pnpm and i just can`t simply zip node_modules, because pnpm uses symlinks. Or maybe i need to resolve them before passing to zip. Maybe you have any ideas on it?

**Comment by khuezy** [comment]
I use `hoisted` for my `pnpm` and it worked. The reason why we need `external: ['next']` is because `nextjs` requires (or perhaps loads some next libs dynamically) so we can't bundle the code. That may or may not have changed in v14.

**Comment by r34son** [comment]
Yeah, got you, thanks.

It dynamically requires `"@opentelemetry/api"`, `"critters"`, `"styled-jsx"` and etc.

**Comment by conico974** [comment]
Just bundling into CJS won't be enough if you want to deploy outside of AWS and without ESM.
In V2 there is a lot of dependencies to AWS (S3, SQS, DynamoDB, Cloudfront, Lambda event) that you'll have to replace if you want everything to work.
For example [this](https://github.com/sst/open-next/blob/main/packages/open-next/src/adapters/event-mapper.ts) will need to be rewritten.
> i just can`t simply zip node_modules, because pnpm uses symlinks

zip command (at least on linux) will properly copy the symlinks you need.
One other reasons why you can't just bundle next is that the build output of next also depends on `node_modules`

**Comment by r34son** [comment]
I am using terraform to archive lambda, maybe i need some additional options to pass, but i tried pnpm hoisted setting and it easily solves my issue
