### ISSUE TITLE
Duplicating location header

### ISSUE THREAD

**Issue by r34son** [sst/open-next#368]
I'm using `next-intl`. Server function handles redirect from middleware, but there is an issue that it duplicates `location` header because of case mismatch.

```
"headers": {
    "location": "https://someurl.com/some-path",
    "Location": "https://someurl.com/some-path"
},
```

**Comment by r34son** [comment]
https://github.com/sst/open-next/blob/3deb2022d0bb506e4c4b66baeae248c7c2b153e5/packages/open-next/src/adapters/routing/middleware.ts#L136

Here `resHeaders` contain location key

**Comment by khuezy** [comment]
Clients and servers are suppose to handle either casing right? But in general, they should be pascal casing. Can you figure out where/what is setting it to the lower case `location` and fixing that? If that's somewhere upstream, then we should delete it from the `resHeaders` to remove the duplication.
