### ISSUE TITLE
Middleware ignored when deploying to prod

### ISSUE THREAD

**Issue by EAlf91** [sst/open-next#376]
I've been struggling with this for a while now

I use latest nextjs 14 using the app router and put my middleware.ts into the root of my project as the documentation suggests.

When running npm run dev locally everything works fine and the middleware triggers.

But when running a deployment and I hit the cloudfront routes I just get routed through. No middleware is being triggered. 

This is a serious issue as it makes secured routes public available.

This is my middleware setup:

```
/**
 * BIG WARNING
 * THIS IS NOT WORKING IN PROD middleware seems to be ignored
 */
'use client'
import { fetchAuthSession } from 'aws-amplify/auth/server';
import { NextRequest, NextResponse } from 'next/server';
import { runWithAmplifyServerContext } from '@/utils/amplifyServerUtils';
import { LINKS } from '@/utils/links/links';

export async function middleware(request: NextRequest) {
  const response = NextResponse.next();
  const authenticated = await runWithAmplifyServerContext({
    nextServerContext: { request, response },
    operation: async (contextSpec) => {
      try {
        const session = await fetchAuthSession(contextSpec);
        return session.tokens !== undefined;
      } catch (error) {
        console.log(error);
        return false;
      }
    },
  });

  if (authenticated) {
    return response;
  }

  return NextResponse.redirect(new URL(LINKS.ROOT_AUTH_LOGIN, request.url));
}

export const config = {
  matcher: [
    '/api/login/'
  ]
};

**Comment by conico974** [comment]
Are you running on windows? Open-next don't work well there, you need to use WSL

**Comment by EAlf91** [comment]
@conico974 Thanks! Just deployed on wsl and it worked. Would have never guessed that this was the problem. You saved me tons of time. 👍 I'll close the issue
