### ISSUE TITLE
open-next vs nodejs-server

### ISSUE THREAD

**Issue by smith558** [sst/open-next#382]
From your website https://github.com/sst/open-next:

> Next.js, unlike Remix or Astro, doesn't have a way to self-host using serverless. You can run it as a Node application. This however doesn't work the same way as it does on Vercel.

Is that the case though? Why is it not enough though just follow the guide at https://nextjs.org/docs/app/building-your-application/deploying#nodejs-server? Am I missing anything? For my use case, I am not interested in [Vercel Functions](https://vercel.com/docs/functions#).

I know these are the features that require server runtime:
- [Dynamic Routes](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes) with dynamicParams: true
- [Dynamic Routes](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes) without generateStaticParams()
- [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers) that rely on Request
- [Cookies](https://nextjs.org/docs/app/api-reference/functions/cookies)
- [Rewrites](https://nextjs.org/docs/app/api-reference/next-config-js/rewrites)
- [Redirects](https://nextjs.org/docs/app/api-reference/next-config-js/redirects)
- [Headers](https://nextjs.org/docs/app/api-reference/next-config-js/headers)
- [Middleware](https://nextjs.org/docs/app/building-your-application/routing/middleware)
- [Incremental Static Regeneration](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating)
- [Image Optimization](https://nextjs.org/docs/app/building-your-application/optimizing/images) with the default loader
- [Draft Mode](https://nextjs.org/docs/app/building-your-application/configuring/draft-mode)

For those, shouldn't a simple Node.js server be enough?

**Comment by conico974** [comment]
I think you missed the point of this sentence
> Next.js, unlike Remix or Astro, doesn't have a way to self-host using **SERVERLESS**

The next sentence then just says 
> You can run it as a Node application

So yeah you're right a simple Node.js server is enough for those cases. If you're not interested in serverless and want to run next on a single server, then open-next is not the right tools for you.

If we're talking about serverless, then there is a lot of stuff that need to be done to make it work properly.

I'll close this as it's not really an issue
If you want to talk more about open-next you can join the [discord](https://discord.com/channels/983865673656705025/1027265626085019769)
