### ISSUE TITLE
vercel.svg, favicon.ico, and next.svg was retrieve from disk cache and cloudfront.

### ISSUE THREAD

**Issue by VanThanh12195** [sst/open-next#383]
Greetings everyone,

I've utilized the initial Next.js project for deploying to AWS using SST and OpenNext for testing purposes.

Upon inspecting the Network tab, I noticed that the vercel.svg, favicon.ico, and next.svg were retrieved both from the disk cache (as expected) and also from CloudFront. I'm puzzled as to why these images were fetched twice. Interestingly, when I attempted to deploy this to Vercel, this issue did not occur.

Please refer to the image below for better clarification.

![image](https://github.com/sst/open-next/assets/14349308/6251f328-43a1-486d-bf75-57b1ff76be2d)

**Comment by conico974** [comment]
This is an sst issue, and you can customize it if you want, just set 
```ts
assets: {
  "nonVersionedFilesCacheHeader": "WHATEVER_YOU_WANT",
}
```
https://github.com/sst/sst/blob/dd82a1fdf72dd517441e9507659c377cf2d7df32/packages/sst/src/constructs/SsrSite.ts#L327-L337
