### ISSUE TITLE
Image optimizarion break on Nextjs 14.1

### ISSUE THREAD

**Issue by VanThanh12195** [sst/open-next#384]
It seems like image optimization does not work on Opennext:

Image below is the screenshort for image optimization lambda function: 
![image](https://github.com/sst/open-next/assets/14349308/285673a4-4647-47f5-a77f-3c467f6dc577)

**Comment by khuezy** [comment]
Hi, can you specify your `next` and `open-next` version?

**Comment by conico974** [comment]
It is also not the correct way to access this function. 
You're accessing the lambda directly, you need to access it with an url like that : `/_next/image?url=https%3A%2F%2Fopen-next.js.org%2Farchitecture.png&w=840&q=75`

**Comment by VanThanh12195** [comment]
> Hi, can you specify your `next` and `open-next` version? This might be a duplicate issue: #374

I use Nextjs 14.1.3 and open-next  2.3.7

**Comment by VanThanh12195** [comment]
> It is also not the correct way to access this function. You're accessing the lambda directly, you need to access it with an url like that : `/_next/image?url=https%3A%2F%2Fopen-next.js.org%2Farchitecture.png&w=840&q=75`

I tried this: and got this error : "Cannot read properties of undefined (reading '0')"

**Comment by conico974** [comment]
It looks like the open-next plugin is not applied
@VanThanh12195  Are you building on windows ? You should use WSL there

**Comment by VanThanh12195** [comment]
> It looks like the open-next plugin is not applied @VanThanh12195 Are you building on windows ? You should use WSL there

yes I am using win 11

**Comment by conico974** [comment]
I'll close all the windows related issue in favor of https://github.com/sst/open-next/issues/385
