### ISSUE TITLE
[Edge] Set-Cookie headers are concatenated

### ISSUE THREAD

**Issue by dg-lucasvieira** [sst/open-next#386]
#### Issue

When the Next.js App is deployed to AWS Lambda@Edge and there is more than one `set-cookie` header in the response, the CloudFront response concatenates the entries into one `set-cookie` item.

#### Example

Header: `set-cookie`: `test=1; Path=/; HttpOnly; Secure; SameSite=None, test=2; Path=/; HttpOnly; Secure; SameSite=None`

and it should be:

`set-cookie`: `test=1; Path=/; HttpOnly; Secure; SameSite=None`
`set-cookie`: `test=2; Path=/; HttpOnly; Secure; SameSite=None`

**Comment by khuezy** [comment]
Hi thanks for the report. Is this specific to L@E or does this happen everywhere?

**Comment by lucasvieirasilva** [comment]
I've only tested in the L@E, but looking at OpenNext's code the other places seem to be right.

I've raise a PR for that https://github.com/sst/open-next/pull/387

**Comment by conico974** [comment]
Fixed in open-next@2.3.8 by https://github.com/sst/open-next/pull/387
