### ISSUE TITLE
Nextjs doesn't have "copyFiles" property

### ISSUE THREAD

**Issue by aquarazorda** [sst/open-next#403]
Pre ion, `NextjsSite` construct had a `cdk` prop and from there, via `server.copyFiles` you could have added an array of files.
In ion, only Function has `copyFiles` prop. I guess Nextjs is missing it, since Dax told me to open this issue.

**Comment by khuezy** [comment]
Hmm is this the correct repository? `NextjsSite` is related to https://github.com/sst/sst

**Comment by aquarazorda** [comment]
> Hmm is this the correct repository? `NextjsSite` is related to https://github.com/sst/sst

You are absolutely correct. I've been thinking about open-next too much lately. Because of the streaming, I've opened this issue instinctively.

I'm taking it to sst repo.

Thanks
