### ISSUE TITLE
Lambda@Edge tried to add, delete, or change a read-only header

### ISSUE THREAD

**Issue by tsurumeso** [sst/open-next#427]
Next.js version: 12.3.4

Hi, I am running a server function on Lambda@Edge with OpenNEXT.
```
# open-next.config.ts
import type { OpenNextConfig } from 'open-next/types/open-next';

const config = {
  default: {
    override: {
      converter: 'aws-cloudfront',
    },
  },
  imageOptimization: {
    arch: 'x64',
  },
  dangerous: {
    disableTagCache: true,
    disableIncrementalCache: true,
  },
} satisfies OpenNextConfig;

export default config;
export type Config = typeof config;
```
This application worked with open-next@3.0.0, but not with open-next@3.0.1.
Specifically, the following error is displayed when accessing API Routes.
```
The Lambda function result failed validation: The function tried to add, delete, or change a read-only header. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
```

I think the cause is that a read-only Content-Length header is added.
```
# Debug log for open-next@3.0.0
INFO	{
  status: '200',
  statusDescription: 'OK',
  headers: {
    'cache-control': [ [Object] ],
    'content-type': [ [Object] ],
    etag: [ [Object] ],
    'X-OpenNext': [ [Object] ],
    'X-OpenNext-Version': [ [Object] ],
    'X-OpenNext-RequestId': [ [Object] ]
  },
  bodyEncoding: 'text',
  body: ...
}
```
```
# Debug log for open-next@3.0.1
INFO	{
  status: '200',
  statusDescription: 'OK',
  headers: {
    'cache-control': [ [Object] ],
    'content-type': [ [Object] ],
    etag: [ [Object] ],
    'content-length': [ [Object] ],
    'X-OpenNext': [ [Object] ],
    'X-OpenNext-Version': [ [Object] ],
    'X-OpenNext-RequestId': [ [Object] ]
  },
  bodyEncoding: 'text',
  body: ...
}
```

Can this be fixed?

**Comment by conico974** [comment]
Hmm i see, it's caused by this commit https://github.com/sst/open-next/commit/3b004dda67af90e077f1237aea38966e7d2ffd92. We need to find a proper way of dealing with that.

In the meantime, you can update OpenNext to 3.0.2 and just use this https://open-next.js.org/config/custom_overrides#custom-converter. 
Instead of adding stuff you just remove the headers you don't want, and use aws-cloudfront as the converter instead of aws-apigw-v2

**Comment by tsurumeso** [comment]
Thanks for the reply.
I'll try this until it's fixed!
> In the meantime, you can update OpenNext to 3.0.2 and just use this https://open-next.js.org/config/custom_overrides#custom-converter.
> Instead of adding stuff you just remove the headers you don't want, and use aws-cloudfront as the converter instead of aws-apigw-v2
