### ISSUE TITLE
Open next with SST on AWS - Missing Cloudfront Behaviors

### ISSUE THREAD

**Issue by Archie-Cloudbuddies** [sst/open-next#462]
Hi everyone, Greg here founder of https://cloudbuddies.io/, nice to meet you. 

We were running for quite some months an SST stack on AWS with opennext hosting our Application (cloud self-service platform). All was fine until 21st of June. Yesterday I wanted to update the stack like I usually do and noticed after that, that my login function (nextauth api) is not working anymore and throws a 500 error.

I reviewed the cloudfront configuration and notice some changes in the behaviors compared to previous deployments. 
For example it seems that the api/* route is not created anymore. Maybe others as well, still investigating. Maybe the lambda function running the node server has issues as well.

I also analysed the CF template from the stack created and don't find the behavior (path pattern) for the /api route neither.

Any support possible ?
You can try the login on the application here : https://archie-sandbox.cloudbuddies.io/ 

Available if further details are needed. Thanks for the support.
Also if we refer to the architecture diagram visible in the open next doc, we  see that the API route is sent to the lambda server function.

**Comment by conico974** [comment]
The `api/*` behavior is not needed, all the route will go to the default function. That is not your issue here.
@Archie-Cloudbuddies What version of Next, OpenNext and SST are you using ?
Have you looked at the cloudwatch logs ?

**Comment by Archie-Cloudbuddies** [comment]
Hey @conico974 thanks for taking time to reply. 

Oh interesting I thought it was needed as visible on the diagram here (https://open-next.js.org/inner_workings/architecture), but fine.

Here are the answers, this is shown when I do npx sst deploy

> SST v2.43.3
> Next.js version : 14.2.1
> OpenNext v3.0.2

Yes I had some look in cloudwatch logs, I found this in the sitedefaultserverfunction log, but not sure if it's related

```
2024-07-04T13:25:04.393Z	98945a3a-7e27-43e1-88b2-95e8f9cea134	ERROR	[next-auth][error][NO_SECRET] 
https://next-auth.js.org/errors#no_secret Please define a `secret` in production. r [MissingSecretError]: Please define a `secret` in production.
```

Also I have a nextauth secret in my env. file.

**Comment by conico974** [comment]
There was an issue in this version of OpenNext that didn't copy .env file. Updating OpenNext to the latest (i.e. 3.0.6 ) should be enough https://docs.sst.dev/constructs/NextjsSite#opennextversion.
You can close the issue if it did solve it

**Comment by Archie-Cloudbuddies** [comment]
OK, will try and let you know or close the issue if fixed.

**Comment by Archie-Cloudbuddies** [comment]
Looks like I have the latest open next install 3.06 (when i run a local build with yarn build)

> npx open-next@latest build
> Next.js version : 14.2.1
> OpenNext v3.0.6

but when I do the sst deploy it seems that it is not using the latest version (as it also does a build before creating the infra) 

> npx sst deploy
> Please enter a name you’d like to use for your personal stage. Or hit enter to use: archie-sandbox
> SST v2.43.3
> 
> ➜  App:     nextjs-home
>    Stage:   archie-sandbox
>    Region:  us-east-1
>    Account: 7xxxxxxxxx
> 
> Next.js version : 14.2.1
> OpenNext v3.0.2

...any additional help u can provide ?

**Comment by conico974** [comment]
You need to set `openNextVersion` in the NextJsSite construct. Just like in the link i provided above 
SST doesn't pick the version of OpenNext you installed ( i assume you installed it with npm/pnpm/yarn ), you need to provide it as i showed or change the buildCommand ( same thing it's in the NextJsSite construct )

**Comment by Archie-Cloudbuddies** [comment]
Fixed by conico974 recommendation (opennextversion in construct)
