### ISSUE TITLE
Next config redirects is not working correctly with i18n default platform

### ISSUE THREAD

**Issue by FR073N** [sst/open-next#466]
We are experiencing an issue with the "redirects" feature in Open Next when deploying on AWS. We are using the latest versions:

- Next.js: 14.2.
- Open Next: 2.3.9 (also tested on 3.0.6)

In our setup, we use [i18n mode](https://nextjs.org/docs/pages/building-your-application/routing/internationalization) with domains for both 'en' and 'fr' at the root level. The redirects specified in the next.config.js file do not function correctly at the root level for the default domain.

**next.config.js :** 
```javascript
const nextConfig = {
  pageExtensions: ['page.tsx', 'routing.ts'],
  compiler: {
    styledComponents: true
  },
  i18n: {
    defaultLocale: 'fr',
    locales: ['fr', 'en'],
    localeDetection: false
  },
  redirects: async () => {
    return [
      {
        source: '/twitch',
        destination: '/live',
        permanent: false
      }
    ];
  },
```

What will happen :
- `/en/twitch` -> will redirect to `/en/live`
- `/fr/twitch` -> will redirect to `/fr/live`
- `/twitch` -> 404

This issue does not occur in our local environment. The redirects work perfectly when using `next build` and `next start` locally. The problem seems to be specific to deployments with Open Next on AWS.

Could you please assist us in resolving this issue?

Thank you for your help.

**Comment by sommeeeer** [comment]
Try updating open-next to `3.0.6`. There was a commit trying to fix this issue there: https://github.com/sst/open-next/releases/tag/v3.0.6

**Comment by sommeeeer** [comment]
try using `open-next` with version `3.0.6`, there was some commits trying to solve some issues related to i18n in that release. can't however guarantee it will work, but its worth a shot!

**Comment by Ryad-T** [comment]
Facing the same issue here. I was also using a not up-to date version of open-next so I updated to 3.0.6 as suggested by @sommeeeer but doesn't seems to do the trick here.

I'm using Terraform to deploy my stack (also on AWS) with one of the recommended solution to do so (but customized)

**Comment by FR073N** [comment]
> try using `open-next` with version `3.0.6`, there was some commits trying to solve some issues related to i18n in that release. can't however guarantee it will work, but its worth a shot!

Unfortunately it didn't do the trick for me neither. 

Currently, we banned the redirection with next features, and we are redirecting on infrastructure side. But this is not a long term solution. Can we do something to help ?

**Comment by conico974** [comment]
Yeah i18n is not properly handled in OpenNext for next config redirect and rewrite right now.
If you want to try to tackle this issue right now, this is the code responsible for handling rewrites and redirect. https://github.com/sst/open-next/blob/1a1441cd462bb3b09a5d0fd75bd21a661762f684/packages/open-next/src/core/routing/matcher.ts#L168-L238
I think to fix it, we'll need to localize the rawPath used in L177 and L198 ( only if using i18n of course )
I'll try to work on this by the end of the week anyway
