### ISSUE TITLE
Potential Bug in OpenNext Cache Adapter or Incorrect CloudFront Cache Invalidation Examples in the Docs

### ISSUE THREAD

**Issue by mlukasik-dev** [sst/open-next#495]
I wanted to test the `getByTag` function from [the docs](https://open-next.js.org/inner_workings/caching#cloudfront-cache-invalidation) on my website with ISR pages and using cache tags.
For some pages cache adapter creates DB entries correctly, so we are able to get list of path where given tag is used.
But for some pages the only entry in the DB is for a path in the format of `BUILD_ID/FETCH_ID` instead of `BUILD_ID/path/subpath`.

I suspect that the CloudFront invalidation is not tested very thoroughly in the latest versions, because the code in the docs contains typos :)

Let me know how I can provide more relevant information. Thank you!

**Comment by khuezy** [comment]
Hey can you link the typo? The only thing I can see if the missing `async` in `function getByTag(tag: string) {`

**Comment by conico974** [comment]
Are those page generated at build time ? If the page has not been generated at build time there is nothing at first in DDB (It should get populated after the page has been accessed once)

The page that are not there are ISR or SSG right ? SSR page could still generate some fetch cache, but you will never get the path with the `getByTag` function (You don't need to invalidate anything in this case)

You probably want to avoid using the `getByTag` as much as possible anyway for cloudfront invalidation. You should probably use glob pattern (i.e. `/path/*` ) as much as you can because cloudfront invalidation can become very costly very fast otherwise

**Comment by mlukasik-dev** [comment]
> Hey, can you link the typo? The only thing I can see is the missing `async` in `function getByTag(tag: string) {`

@khuezy. I've noticed 3 "typos":
- `error` instead of `console.error` (not necessarily a typo)
- `this` cannot be used in this context (it is neither a class method nor an object property)
- and as you mention, missing `async`

**Comment by khuezy** [comment]
@mlukasik-dev Thanks, do you mind putting a PR w/ the fixes.

**Comment by mlukasik-dev** [comment]
> Are those page generated at build time ? If the page has not been generated at build time there is nothing at first in DDB (It should get populated after the page has been accessed once)
> 
> The page that are not there are ISR or SSG right ? SSR page could still generate some fetch cache, but you will never get the path with the `getByTag` function (You don't need to invalidate anything in this case)
> 
> You probably want to avoid using the `getByTag` as much as possible anyway for cloudfront invalidation. You should probably use glob pattern (i.e. `/path/*` ) as much as you can because cloudfront invalidation can become very costly very fast otherwise


1. pages are generated at runtime. I've done some experient by visiting the page and looking at what is generated in DDB.
2. these pages are ISR that live under `app/[lang]` and I return an empty array from `generateStaticParams`. So they are not SSR.
3. yeah, that was more of an experiment, so I'm not sure if I'll use it, but anyway in my situation if I handle output of `getByTag` properly my invalidations will be more cost effective.

**Comment by mlukasik-dev** [comment]
> @mlukasik-dev Thanks, do you mind putting a PR w/ the fixes.

Sure.

**Comment by conico974** [comment]
If the page is ISR or SSG it should be populating properly after the page has been accessed https://github.com/sst/open-next/blob/c91c83b5c84c1ea582c03eb23250239954343b64/packages/open-next/src/adapters/cache.ts#L332-L343
You sure that they are ISR ? ( You can look at the cache-control header it should be something like `s-maxage=12345, stale-while-revalidate=2592000` )

If they are in fact ISR/SSG, then you'll need to create a reproduction as this should work

**Comment by mlukasik-dev** [comment]
I checked the response headers and those pages did indeed have SSR. I forgot to include `generateStaticParams' in the layout of those specific pages. I confirm that everything is now working correctly and the issue can be closed.
Thanks for your help @khuezy and @conico974!
