### ISSUE TITLE
Stale deployment pipeline

### ISSUE THREAD

**Issue by diogoparente** [sst/open-next#59]
Hey folks,

I'm currently building a pipeline that goes through all the steps. The problem is that after bundling assets, it stales.
Anyone experienced the same?

Thanks

<img width="752" alt="Screenshot 2023-03-27 at 09 21 27" src="https://user-images.githubusercontent.com/66437099/227888545-bc13c4b8-8bd1-478d-af47-28e15eaf34f7.png">

**Comment by sladg** [comment]
@diogoparente can you provide example?
I experienced stalling, but never at building phase. Can you try running `next build` on it's own if it passes?

**Comment by diogoparente** [comment]
Hey @sladg . I'm afraid I completely forgot the context of this, so I'm going to close the issue.
Cheers and thanks for helping.
