### ISSUE TITLE
production concerns for critical project

### ISSUE THREAD

**Issue by devmanbr** [sst/open-next#85]
since I found open-next, I've been very excited, and I really hope it continues to be maintained and grows more and more.

however, currently I've been seeing some bug reports that are a little worrying, and I'm about to start a next.js project where I intended to use this project.

in your opinion, is open-next ready for production?
should I know of something that isn't already in the documentation or that someone experienced differently than expected?

**Comment by devmanbr** [comment]
thank you so much for answering!

the functioning of the ISR and API routes were the situations that led me to concerns.

to be more precise, as I'm not an expert on how next.js works in depth, I'm not sure I'm essentially capable of pointing out more specific issues. I know the features and APIs as they are presented in the next.js formal documentation, but I don't know how they work in the background.

I opened the topic to be a little more sure about the stability to avoid unexpected behavior, since that was the point where my client was more incisive.

I just need to know it works before I start 😅

**Comment by sladg** [comment]
I'm currently working on migrating all our Next projects to open-next with all of them being in production. I figured that as long as you are not relying on the most bleeding edge features, this is fairly stable and after trying, there is very little concern. If you can live with outdated Next version and features for couple of month (aka. you are not awaiting some major change/improvement) you should be good to go.

PS. if you are on `"next": "latest"` in your `package.json`, Vercel is probably a way to go

**Comment by khuezy** [comment]
We recently added e2e tests (unit tests still need to be set up), but for the most part it should be stable. #208 fixes most of the ISR issues except the app router invalidation. That and streaming is next to be fixes/supported.
