### ISSUE TITLE
request for community feedback: multiple cloud providers considerations

### ISSUE THREAD

**Issue by devmanbr** [sst/open-next#89]
I'm about to start a project where my client intends to use AWS, but together with another CDN provider (including considering another serverless provider, or mixed approach). this impacts directly on the open-next aspect.

Has anyone in the community tried to make use of different cloud services together with next.js and open-next and did it work? how was the setup?

p.s. I'm definitely not an expert on how next.js works in the background.

**Comment by conico974** [comment]
It will be possible in open-next V3 https://open-next.js.org/v3
You might have to override some part though

**Comment by conico974** [comment]
Fixed in [V3](https://github.com/sst/open-next/releases/tag/v3.0.0)
