### ISSUE TITLE
Infrastructure as code support

### ISSUE THREAD

**Issue by swve** [sst/open-next#9]
Hey OpenNext 👋🏻
Amazing project and thanks a lot for the effort ! 

I was wondering if you guys are planning to support Infra as code as part of the project, tools like Terraform (multi-cloud) can help create the AWS/GCP infrastructure for OpenNext as simple as running one command. 

The terraform code will be in form of configuration code and it's mostly yaml-like files, I believe this will help users instantly create Lambdas, CloudFront CDNs etc, with the configuration required for OpenNext to run, a way to "Standarize" deployments.

Also Google Cloud users (& other clouds) will be able to deploy OpenNext infra too, so no Cloud Provider lock-in 😁

I offer to personally help with this task if you guys like the idea.

Thanks!

**Comment by sladg** [comment]
Other people pointed me here, so I will do the same 😬 https://github.com/sladg/nextjs-lambda if you want to deploy to AWS.

@jayair @fwang let me know if it would make sense to talk considering the similar scope of our packages :)

**Comment by fwang** [comment]
Hey @sladg, a lot of what I did is inspired by nextjs-lambda, and the serverless-next.js project. Meant to reach out after getting OpenNext gets to v1. I think there's much value to combing our efforts.

@swve I'm hoping OpenNext to become this tool where ppl pick the adapter they want to use (currently only AWS), and it spits out the assets (`server` code, `image-optimizer` code, `middleware` code, and `assets`) you can deploy as is. At the moment, I wonder if it makes sense to decouple the infrastructure from the code, and let the community create ie.`open-next-cdk` or `open-next-terraform`.

Totally open to suggestions.

**Comment by swve** [comment]
Hi @fwang 

I think it depends on allocated time available to this project, as you said it makes more sense to focus on the actual code and tool instead of managing (repo) the Infrastructure code too, 

But as you said it would be great if the CLI could generate the assets and also let the user choose the adapter (cloud service) & generate the terraform code for it letting the user deploy the infrastructure later (using terraform commands etc) the generated code would be taken from a community-led repo or a repository hosted on your organisation and managed by the community && OpenNext core contributors.

Something like `serverless-stack/open-next-infra` with folders for every IaC tool : 

```
- terraform/aws
- terraform/gcp
- aws/cdk 
- aws/cloudformation
```
But again I know managing open source repos can be an additional overhead so I guess it depends on time allocated to the project 😊

Cheers!

**Comment by coltenkrauter** [comment]
I'm excited about where this is going. So, I'm in process of ditching the unsupported `@sls-next/cdk-construct`, but I still want to deploy my app to AWS Lambda (or Lambda@Edge) using CDK. Is [sladg/nextjs-lambda](https://github.com/sladg/nextjs-lambda) my best bet at this point?

**Comment by williamrjribeiro** [comment]
So, if I understood correctly, my NextJS could be built and transformed with OpenNext and then deployed using `sladg/nextjs-lambda`, right?

Sounds promising but has anyone been able to achieve it already? If so, can you share it, please?

**Comment by sladg** [comment]
We can close this I assume? We have CDK construct in: https://github.com/sst/sst/blob/master/packages/sst/src/constructs/NextjsSite.ts

**Comment by conico974** [comment]
As mentionned by @sladg there is the SST construct, but there is also some other frameworks
https://github.com/sst/open-next#other-frameworks.
