### ISSUE TITLE
open-next monorepo

### ISSUE THREAD

**Issue by dianasecrieru** [sst/open-next#96]
Does anyone have an example using open-next in a monorepo project?

**Comment by khuezy** [comment]
https://github.com/serverless-stack/open-next/tree/main/example has the basics. You can pick your monorepo library and plug it in.

**Comment by brianjutrzonka** [comment]
I might be a little lost looking at that example.  Do you have an example with something like an NX Monorepo?

**Comment by khuezy** [comment]
NX is over engineered imo. This repo might be outdated: https://github.com/nowlena/sst-nx

**Comment by masterbater** [comment]
> NX is over engineered imo. This repo might be outdated: https://github.com/nowlena/sst-nx

Are you insulting the work of multiple dedicated engineers. Any software that is widely used is not over engineered, they just cover everything including rough edges. Dont invalidate the effort of those talented people be thankful they are giving us free meal, some monorepos get inspiration from them. I personally do use turborepo for its simplicity hehe.

**Comment by khuezy** [comment]
> > NX is over engineered imo. This repo might be outdated: https://github.com/nowlena/sst-nx
> 
> Are you insulting the work of multiple dedicated engineers. Any software that is widely used is not over engineered, they just cover everything including rough edges. Dont invalidate the effort of those talented people be thankful they are giving us free meal, some monorepos get inspiration from them. I personally do use turborepo for its simplicity hehe.

How on earth did you interpret that as an insult??? It's a fact. If your project requires such complexity then use NX, but for most scenarios it is overkill.

**Comment by khuezy** [comment]
The `main` branch uses turbo repo, perhaps that can give you an idea how to set one up. As for `nx`, you'll need to ask someone w/ experience.
